fix(LT-5045): no need to raise another exception when coudln't insert…
LykkeBusiness/MarginTrading.OrderBookService pull request #44
Opened 2023-10-18 20:28 UTC by tarurar

… new record into dbo.ExecutionOrderBooks

2023-11-13 08:49 UTC, gponomarev-lykke requested changes

2023-11-13 08:49 UTC, gponomarev-lykke commented on MarginTrading.OrderBookService.SqlRepositories/ExecutionOrderBookRepository.cs
> +go
I'm almost sure this statement only works in SSMS

https://learn.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver16


```
GO is not a Transact-SQL statement; it is a command recognized by the sqlcmd and osql utilities and SQL Server Management Studio Code editor.
```

2023-11-14 13:43 UTC, tarurar commented on MarginTrading.OrderBookService.SqlRepositories/ExecutionOrderBookRepository.cs
> +go
Well, my bad. Fixed.

2023-11-15 06:57 UTC, gponomarev-lykke approved these changes

2023-11-15 07:01 UTC, merged